---
jdbc_connection:
  name: "otk_and_mag"
  owner: "layer7"
  group: "layer7"
  ssl_port: 9443
  file:
    src: "roles/otk/files/jdbc_connection.j2"
    dest: '/var/tmp/otk_jdbc_connection.xml'
  api_url: '/restman/1.0/jdbcConnections'
  id_xml_tag: 'l7:Id'
  id_regex: 's,.*<l7:Id>\([^<]*\)</l7:Id>.*,\1,g'
  curl_log: '/var/tmp/restman_jdbc_connection.log'
cassandra_connection:
  # OTK Cassandra connection name limitation: https://docops.ca.com/ca-api-management-oauth-toolkit/3-3/installation-workflow/create-or-upgrade-the-otk-database/apache-cassandra-database
  name: "OAuth_Cassandra"
  owner: "layer7"
  group: "layer7"
  ssl_port: 9443
  file:
    src: "roles/otk/files/cassandra_connection.j2"
    dest: '/var/tmp/otk_cassandra_connection.xml'
  api_url: '/restman/1.0/cassandraConnections'
  id_xml_tag: 'l7:Id'
  id_regex: 's,.*<l7:Id>\([^<]*\)</l7:Id>.*,\1,g'
  curl_log: '/var/tmp/restman_cassandra_connection.log'
