---
cluster_property:
  name1: "restman.request.message.maxSize"
  value1: "102400"
  ssl_port: 9443
  file:
    src: "roles/gmu/files/cluster_property.j2"
    dest: '/var/tmp/cluster_property.xml'
  api_url: '/restman/1.0/clusterProperties'
  id_xml_tag: 'l7:Id'
  id_regex: 's,.*<l7:Id>\([^<]*\)</l7:Id>.*,\1,g'
  curl_log: '/var/tmp/restman_cluster_property.log'
aws_env_bundle:
  ssl_port: 9443
  file:
    src: "roles/gmu/files/localTwilio.j2"
    dest: "/var/tmp/localTwilio.xml"
  curl_log: "/var/tmp/bundle_import.log"
  api_url: "/restman/1.0/bundle?test=false&activate=true"
cluster_property2:
  name2: "io.xmlPartMaxBytes"
  value2: "104857600"
  ssl_port: 9443
  file:
    src: "roles/gmu/files/cluster_property2.j2"
    dest: '/var/tmp/cluster_property2.xml'
  api_url: '/restman/1.0/clusterProperties'
  id_xml_tag: 'l7:Id'
  id_regex: 's,.*<l7:Id>\([^<]*\)</l7:Id>.*,\1,g'
  curl_log: '/var/tmp/restman_cluster_property.log'