---
## Note this file is only stored for demo purposes. Any production credentials should not
## be included in version control.
mosquitto_packages:
  owner: "root"
  group: "root"
  main:
    src: "/Users/pagch04/API/apim_vagrant_ansible_files/mosquitto-1.4.8-1.1.x86_64.rpm"
    dest: "/var/tmp/mosquitto-1.4.8-1.1.x86_64.rpm"
  clients:
    src: "/Users/pagch04/API/apim_vagrant_ansible_files/mosquitto-clients-1.4.8-1.1.x86_64.rpm"
    dest: "/var/tmp/mosquitto-clients-1.4.8-1.1.x86_64.rpm"
  lib:
    src: "/Users/pagch04/API/apim_vagrant_ansible_files/libmosquitto1-1.4.8-1.1.x86_64.rpm"
    dest: "/var/tmp/libmosquitto1-1.4.8-1.1.x86_64.rpm"
  tcp_wrappers:
    src: "/Users/pagch04/API/apim_vagrant_ansible_files/tcp_wrappers-7.6-57.el6.x86_64.rpm"
    dest: "/var/tmp/tcp_wrappers-7.6-57.el6.x86_64.rpm"
  uuid:
    src: "/Users/pagch04/API/apim_vagrant_ansible_files/uuid-1.6.1-10.el6.x86_64.rpm"
    dest: "/var/tmp/uuid-1.6.1-10.el6.x86_64.rpm"
