---
## Note this file is only stored for demo purposes. Any production credentials should not
## be included in version control.
mas_storage_sk:
  owner: "layer7"
  group: "root"
  ssl_port: 9443
  sskar_file:
    src: "/Users/pagch04/API/apim_vagrant_ansible_files/MAS-Storage-1.2.00-b214.sskar"
    dir: "/var/tmp"
    dest: "/var/tmp/MAS-Storage-1.2.00-b214.sskar"
  api_url: '/restman/1.0/solutionKitManagers'
mas_storage_database:
  technology: "cassandra"
  schema: "mas_storage"
  user: "mas_user"
  pass: "7layer"
  host: "localhost"
  port: 9042
  admin:
    user: "root"
    pass: "7layer"
mas_storage_database_files:
  owner: "layer7"
  group: "root"
  cql:
    db_schema:
      src: "roles/mas_storage/files/cassandra_schema.sql.j2"
      dest: "/var/tmp/mas_storage_cassandra_schema.sql"
mas_storage_cloud:
  url: "https://localhost:8443/internal/MAAS"
  # 'TLSOAuthToken', 'TLSOTKFIP'
  security: "TLSOAuthToken"
